import { Theme } from "../theme.slint";
export component VeritaButton inherits Rectangle {
    callback clicked;

    in property <float> scale-on-hover: 1.03;
    in property <duration> animation-duration: 300ms;
    background: touch.has-hover ? Theme.primary.brighter(0.3) : Theme.primary;
    transform-scale: touch.has-hover ? scale-on-hover : 1.0;
    drop-shadow-blur: touch.has-hover ? 18px : 6px;
    animate background, transform-scale, drop-shadow-blur {
        duration: animation-duration;
        easing: ease-in-out;
    }
    drop-shadow-color: Theme.accent.darker(0.3);

    border-radius: 12px;

    VerticalLayout {
        padding: parent.padding;
        alignment: center;
        @children
    }
    touch:=TouchArea {
        mouse-cursor: pointer;
        clicked => root.clicked();
    }
}
