import { Theme } from "../theme.slint";
export component VeritaButton inherits Rectangle {
    in-out property <string> text;
    in-out property <color> text-color: Theme.foreground;
    callback clicked;

    background: Theme.primary;
    drop-shadow-color: Theme.background;
    drop-shadow-blur: 12px;
    border-radius: 12px;

    HorizontalLayout {
        padding: parent.padding;
        @children
    }
    TouchArea {
        clicked => root.clicked();
    }
}
