import { VerticalBox, LineEdit, HorizontalBox } from "std-widgets.slint";
import { IconDisplay, IconSet } from "@lucide";
import { VeritaButton } from "Button.slint";
import { Theme } from "../theme.slint";
import { HorizontalLine } from "Line.slint";

export struct InviteInformation {
    duration: int
}

component InviteRequesterOption inherits VerticalBox {
    in property <string> title;
    in property <string> placeholder;
    in property <InputType> type;
    out property <string> content <=> line.text;
    spacing: 8px;
    alignment: LayoutAlignment.start;
    Text {
        preferred-width: self.min-width;
        preferred-height: self.min-height;
        text:title;
        color: Theme.accent;
    }
    Rectangle {
        preferred-height: line.preferred-height;
        background: Theme.accent;
        border-radius: 12px;
        line:=LineEdit {
            preferred-width: 100%;
            preferred-height: self.min-height;
            placeholder-text: placeholder;
            input-type: type;
        }
    }
}

export component InviteRequester inherits Rectangle{
    out property <int> invite-duration: duration_input.content.to-float();
    callback on-finish(InviteInformation);
    callback on-close-request();
    drop-shadow-blur: 12px;
    drop-shadow-color: Theme.accent;
    background: Theme.background;
    padding: 0px;
    border-radius: 12px;
    Dialog {
        width: root.width;
        height: root.height;
        background: transparent;
        Rectangle {
            border-color: Theme.accent;
            VerticalBox {
                HorizontalBox {
                    Text {
                        text: "Invite Requester";
                        font-size: 18px;
                        font-weight: 800;
                        color: Theme.accent;
                    }
                    VeritaButton {
                        height: icon.height;
                        icon:= IconDisplay {
                            icon: IconSet.X;
                        }
                        clicked => on-close-request();
                    }
                }
                HorizontalLine {
                    background: Theme.accent;
                }
                VerticalBox {
                    duration_input:=InviteRequesterOption {
                        title: "The duration of the invite";
                        placeholder: "The duration in seconds";
                        type: InputType.number;
                        HorizontalLine {
                            background: Theme.accent;
                        }
                    }
                }

                VeritaButton {
                    height: box.preferred-height;
                    box:=HorizontalBox {
                        Text {
                            text: "Finish the invite";
                        }
                        IconDisplay {
                            icon: IconSet.Check;
                        }
                    }
                    clicked => {
                        on-finish({
                            duration:invite-duration
                        });
                    }
                }

            }
        }
    }
}
