import { HorizontalBox, TextEdit, VerticalBox, LineEdit, ScrollView } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { VeritaButton } from "Button.slint";
import { IconDisplay, IconSet } from "@lucide";
import {MessageData, MessageOwner} from "../domain/Message.slint";
export component Message inherits Rectangle {
    in property <string> content;
    in property <color> content-color;
    VerticalLayout {
        padding: 8px;
        Text {
            text: content;
            color: content-color;
            wrap: word-wrap;
        }
    }
    border-radius: 12px;
    drop-shadow-blur: 12px;
    drop-shadow-color: Theme.border;
}

export component MessageList inherits VerticalLayout {
    in-out property <[MessageData]> messages;

    for message in messages: HorizontalBox {
        alignment: message.owner == MessageOwner.User? LayoutAlignment.end : LayoutAlignment.start;
        Message {
            width: 100%;
            content: message.content;
            content-color: Theme.foreground;
            background: Theme.primary;

        }
    }
    spacing: 12px;
}

export component Chat inherits Rectangle {
    in-out property <[MessageData]> messages <=> list.messages;

    callback onSendMsg(string);
    VerticalLayout {
        padding: root.padding;
        ScrollView {
            vertical-stretch: 1;
            list:=MessageList{
                horizontal-stretch: 1;
            }
        }
        alignment: space-between;

        Rectangle {
            HorizontalLayout {
                padding: 8px;
                spacing: 8px;
                input:= LineEdit{
                    text: "";
                    placeholder-text: "What are you thinking?";

                }
                VeritaButton {
                    IconDisplay {
                        icon: IconSet.Send;
                    }
                    background: transparent;
                    drop-shadow-color: transparent;
                    clicked => {
                        onSendMsg(input.text);
                        input.text = "";
                    }
                }
            }
            border-radius: 12px;
            background: Theme.primary;
        }
    }
}
