import { IconDisplay, IconSet } from "@lucide";
import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { Callbacks } from "../callbacks.slint";
export component Notification inherits Rectangle {
    callback on-finish;
    //duration in seconds
    in property <duration> lifetime: 1s;
    in property <brush> progress-bar-color: Theme.accent;
    in property <length> progress-bar-width:3px;
    in property <brush> bell-stroke: Theme.foreground;
    in property <brush> bell-color: Theme.foreground;

    width: layout.min-width;
    height: layout.min-height;

    rect := Rectangle {
        layout := HorizontalLayout {
            spacing: 12px;
            padding: 4px;
            IconDisplay {
                icon: IconSet.Bell;
                stroke: bell-stroke;
                stroke-fill: bell-color;
            }
            Rectangle {
                @children
            }
        }

        border-color: Theme.foreground;
        border-radius: 0px;
        border-width: 1px;
    }

    Rectangle {
        property <float> progress: 1.0;
        property <float> float-lifetime: lifetime / 1s;
        background: progress-bar-color;
        width: rect.width * progress;
        height: progress-bar-width;
        x: rect.x + (rect.width - self.width) / 2;
        y: rect.y - (self.height / (progress-bar-width / 1px));

        Timer {
            interval: 16ms;
            running: progress > 0.0;
            triggered => {
                progress -= 0.016 / float-lifetime;
                if progress <= 0 {
                    on-finish();
                }
            }
        }
    }
}


export component TextNotification inherits Notification {
    in property <string> title;
    in property <string> description;
    in property <int> key;
    on-finish => {
        Callbacks.notify-end(key);
    }
    width: 400px;
    padding: 16px;
    VerticalLayout {
        alignment: LayoutAlignment.stretch;
        title_text:=Text {
            text: title;
            color: Theme.foreground;
            font-size: 18px;
            font-weight: 700;
        }

        Text {
            text: description;
            color: Theme.foreground;
            wrap: word-wrap;
            font-size: 12px;
        }
    }
}
