[package]
name = "verita"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[workspace]
members = [".", "common",  "database", "migration"]

[workspace.dependencies]
libp2p = {version="0.56.0", features = ["tokio","gossipsub", "mdns", "noise", "macros", "tcp", "yamux", "quic", "kad"]}
color-eyre = "0.6.5"
flume = "0.12.0"
sea-orm = {version = "2.0.2", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"]}
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
chrono = "0.4.45"

[dependencies]
database.path="database"
migration.path="migration"
common.path="common"

color-eyre.workspace=true
flume.workspace=true
sea-orm.workspace=true
tokio.workspace=true
tracing.workspace=true
chrono.workspace=true
libp2p.workspace=true

slint = "1.17.1"
tracing-subscriber = "0.3.23"
async-trait = "0.1.92"
bytes = "1.12.1"
argon2 = "0.6.0"
password-hash = "0.6.1"
rand = "0.10.2"
hmac = "0.13.0"
sha2 = "0.11.0"
serde = "1.0.229"
postcard = {version = "1.1.3", features=["alloc"]}
chacha20poly1305 = { version = "0.11.0", features = ["bytes", "zeroize"] }
arboard = {version = "3.6.1", features=["wayland-data-control"]}
bs58 = "0.5.1"

[build-dependencies]
lucide-slint = "1.44.0"
slint-build = "1.16.0"
