import { VeritaDialog } from "../Dialog.slint";
import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { InviteRequesterOption } from "InviteRequester.slint";
import { VeritaButton } from "../Button.slint";
import { IconDisplay, IconSet } from "@lucide";
import { HorizontalLine } from "../Line.slint";
import { Theme } from "../../theme.slint";
export struct InviteSearch {
    invite: string,
    password: string,
}

export component InviteFinder inherits VeritaDialog {
    callback on-finish(InviteSearch);
    title: "Invite Finder";
    VerticalBox {
        VerticalBox {
            invite-input:=InviteRequesterOption {
                title: "The invite received";
                placeholder: "Type the invite you've got";
                type: InputType.text;
                HorizontalLine {
                    background: Theme.accent;
                }
            }
        }
        VerticalBox {
            password-input:= InviteRequesterOption{
                title: "The password for the invite";
                placeholder: "Type the password of the invite";
                type: InputType.password;
            }
        }
        VeritaButton {
            height: box.preferred-height;
            box:=HorizontalBox {
                Text {
                    text: "Finish";
                }
                IconDisplay {
                    icon: IconSet.Check;
                }
            }

            clicked => {
                on-finish({invite: invite-input.content, password: password-input.content})
            }
        }
    }
}
