import { VeritaDialog } from "../Dialog.slint";
import { Invite, InviteSearch } from "../../domain/Invite.slint";
import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { InviteRequesterOption } from "InviteRequester.slint";
import { VeritaButton } from "../Button.slint";
import { IconDisplay, IconSet } from "@lucide";
import { HorizontalLine, VerticalLine } from "../Line.slint";
import { Theme } from "../../theme.slint";


export component InviteContent {
    in property<Invite> invite;
    VerticalLayout {
        alignment: space-between;
        spacing: 4px;

        Text {
            text: "Address: \{invite.address}";
            color: Theme.accent;
            wrap: word-wrap;
        }
        HorizontalLine {}
        Text {
            text: "User ID: \{invite.peer}";
            color: Theme.accent;
            wrap: word-wrap;
        }
        HorizontalLine {}

        VeritaButton {
            padding: 4px;
            HorizontalLayout {
                alignment: center;
                Text {
                    text: "Send Invite";
                }
                IconDisplay {
                    icon: IconSet.Send;
                }

            }
        }
    }
}

export component InviteFinder inherits VeritaDialog {
    callback on-finish(InviteSearch);
    title: "Invite Finder";
    in-out property <string> error;
    in-out property <Invite> invite;
    HorizontalLayout {
        spacing: 12px;
        alignment: space-between;
        VerticalLayout {
            spacing: 4px;
            VerticalBox {
                invite-input := InviteRequesterOption {
                    title: "The invite received";
                    placeholder: "Type the invite you've got";
                    type: InputType.text;
                    HorizontalLine {
                        background: Theme.accent;
                    }
                }
            }

            VerticalLayout {
                password-input := InviteRequesterOption {
                    title: "The password for the invite";
                    placeholder: "Type the password of the invite";
                    type: InputType.password;
                }
            }

            VeritaButton {
                padding: 4px;
                HorizontalLayout {
                    alignment: center;
                    Text {
                        text: "Finish";
                    }
                    IconDisplay {
                        icon: IconSet.Check;
                    }
                }

                clicked => {
                    on-finish({ invite: invite-input.content, password: password-input.content })
                }
            }
        }
        VerticalLine {
            background: Theme.accent;
        }
        InviteContent {
            invite: invite;
        }
    }
}
