import { UIInvite, Invite } from "../../domain/main.slint";
import { Theme } from "../../theme.slint";
import { VeritaButton } from "../Button.slint";
import { VeritaDialog } from "../Dialog.slint";
import { IconDisplay, IconSet } from "@lucide";
import { Callbacks } from "../../callbacks.slint";
import { HorizontalBox, ScrollView } from "std-widgets.slint";

export component InviteInformation inherits HorizontalLayout {
    in property <string> metadata;
    in property <string> content;
    padding: 12px;
    Text {
        text: metadata;
        color: Theme.foreground;
        font-size: 12px;
    }

    Rectangle {
        background: Theme.foreground;
        Text {
            text: content;
            color: Theme.accent;
        }
    }
}

export component InviteItem {
    in property <UIInvite> invite;
    in property <image> qrcode-image: invite.image;
    property <bool> opened-qrcode:false;
    HorizontalLayout {

        VerticalLayout {
            padding: 12px;
            InviteInformation {
                metadata: "Expiring Date";
                content: invite.timestamp;
            }

            InviteInformation {
                metadata: "Is Valid";
                content: invite.valid ? "Yes" : "No";
            }

            if opened-qrcode:Image {
                source: qrcode-image;
                image-fit: fill;
                width: qrcode-image.width * 0.5px;
                height: qrcode-image.height * 0.5px;
            }
        }

        VeritaButton {
            IconDisplay {
                icon: IconSet.Search;
            }

            clicked => {
                opened-qrcode = !opened-qrcode;
            }
        }
    }
}

export component InviteList inherits VeritaDialog {
    callback refresh-invites(int);
    in property <[UIInvite]> invites;
    in property <int> grid-x: 4;
    in-out property <int> page-index: 0;
    ScrollView {

        layout:=VerticalLayout {
            spacing: 12px;
            if invites.length == 0: HorizontalLayout {
                alignment: center;
                vertical-stretch: 1;
                height: 100%;
                Text {
                    text: "No invites found.";
                    color: Theme.accent;
                }
            }
            for invite[index] in invites: InviteItem {
                invite: invite;
            }
        }

    }
    HorizontalBox {
        alignment: space-between;
        VeritaButton {
            IconDisplay {
                icon: IconSet.ArrowLeft;
            }

            clicked => {
                page-index = page-index - 1;
                refresh-invites(page-index);
            }
        }

        VeritaButton {
            width: self.min-width;
            height: self.min-height;
            IconDisplay {
                icon: IconSet.RotateCcw;
            }

            clicked => {
                refresh-invites(page-index);
            }
        }

        VeritaButton {
            IconDisplay {
                icon: IconSet.ArrowRight;
            }

            clicked => {
                page-index = page-index + 1;
                refresh-invites(page-index);
            }
        }
    }
}
