import {NotificationData, MessageData, FoundInvite} from "domain/main.slint";
export global Callbacks {
    callback notify(NotificationData);
    ///Returns a notification data for the given `title` and `description` on the notification
    callback retrieve-notification-for(string, string, duration) -> NotificationData;
    callback notify-end(int);
    callback send-message(MessageData);
    ///Requests an invite with the given `duration` in ms, and the given `password`
    callback request-invite(int, string);
    ///Finds an invite. The first param is the invite itself, and the second, the password
    callback find-invite(string, string) -> FoundInvite;
}
