import { Theme } from "theme.slint";
import { Button } from "std-widgets.slint";
import { VeritaButton } from "components/Button.slint";
import {
    Chat,
    MessageList,
} from "components/Message.slint";
import { Invite } from "domain/Invite.slint";
import { MessageData, MessageOwner } from "domain/Message.slint";
import { NotificationData } from "domain/Notification.slint";
import { Header } from "components/Header.slint";
import { InviteRequester } from "components/invites/InviteRequester.slint";
import { InviteFinder } from "components/invites/InviteFinder.slint";
import { Notification, TextNotification } from "components/Notification.slint";
import { Callbacks } from "./callbacks.slint";

export { Callbacks }

export component App inherits Window {
    title: "My app";
    background: Theme.background;

    in-out property <[NotificationData]> notifications: [];
    in-out property <[MessageData]> messages: [];

    Rectangle {
        width: 100%;
        height: 100%;

        VerticalLayout {

            Header {
                padding: 4px;
                request-invite => {
                    requester.visible = true;
                    invite-finder.visible = false;
                };
                request-friend => {
                    invite-finder.visible = true;
                    requester.visible = false;
                }
            }

            Chat {
                messages: messages;
                onSendMsg(content) => Callbacks.send-message({ content:content, owner: MessageOwner.User });
            }
        }

        requester := InviteRequester {
            width: 50%;
            height: 50%;
            on-close-request => {
                self.visible = false;
            }
            on-finish(invite) => {
                Callbacks.request-invite(invite.duration, invite.password);
                self.visible = false;
            }
        }

        invite-finder := InviteFinder {
            height: 50%;
            width: 50%;
            on-close-request => {
                self.visible = false;
            }
            on-finish(invitesearch) => {
                let x = Callbacks.find-invite(invitesearch.invite, invitesearch.password);
                if x.error != "" {
                    Callbacks.notify(Callbacks.retrieve-notification-for("Error while trying to find invite", x.error, 2s));
                } else {
                    Callbacks.notify(Callbacks.retrieve-notification-for("Successfuly found user", "Found user with address: \{x.invite.address} and peer \{x.invite.peer}", 2s))
                }
            }
        }

        VerticalLayout {
            x: parent.x + (parent.width / 10);
            y: parent.height / 10;
            for notification in notifications: TextNotification {
                key: notification.key;
                title: notification.title;
                description: notification.text;
                lifetime: notification.duration / 1s;
            }
        }
    }
}
